database: sqlite+aiosqlite:///database/data.db
timeout: 2
commands:
  [
    [info, Информация о боте],
    [menu, Основное меню],
    # [settings, Настройки],
    # [upload, Добавить песню],
    # [listen, Слушать песни],
    # [chart, Лучшие песни],
  ]
info: "/settings - настройки анонимного режима
  (в анонимном режиме люди не видят, что именно Вы загрузили трек, а так же не видят ваши комментарии к загруженным трекам)\n
  /upload - загрузить или переслать песню (максимальный размер - 50МБ)\n
  /listen - слушать рандомный трек. После прослушки можно оценить - так он попадет в ваш чарт (или не попадет)\n
  /chart - 5 рандомных высокооцененных (4-5 звезд) трека из вашего или глобального (по среднестатистической оценке) чарта"
